trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
- job: Build
  displayName: 'Build'

  strategy:
    matrix:
      Release:
        BuildConfiguration: Release
      Debug:
        BuildConfiguration: Debug

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: NuGetToolInstaller@0
    displayName: 'Install Nuget'

  - task: NuGetCommand@2
    displayName: 'Restore Packages'
    inputs:
      restoreSolution: '$(Build.SourcesDirectory)/JellyfinUwp.sln'

  - task: VSBuild@1
    displayName: 'Build Client'
    inputs:
      platform: 'x64'
      solution: '$(Build.SourcesDirectory)/JellyfinUwp.sln'
      configuration: '$(BuildConfiguration)'
